name: Publish ngx-cookie-service to NPM
on:
  push:
    ### Publish on new tag release
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install NPM Dependencies
        run: npm i --legacy-peer-deps
      - name: Build project
        run: npm run build --configuration=production
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/ngx-cookie-service/package.json
          access: public
